[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CelLink"
version = "0.1.4"
description = "Cell linking package"

[tool.setuptools.packages.find]
include = ["CelLink*"]
exclude = ["data*", "experiment*", "docs*", "tests*"]