[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CelLink"
version = "0.1.0"
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["description"]
